### ISSUE TITLE
Help Needed!

### ISSUE THREAD

**Issue by mwakaambrose** [mkrakowitzer/actions-googledrive#6]
Hello, thanks for the good work here. However I have a challenge with the action.

Here is the failure

```log
/usr/bin/docker run --name mkrakowitzeractionsgoogledrivelatest_ffc636 --label 3bec5f --workdir /github/workspace --rm -e JAVA_HOME_8.0.302_x64 -e JAVA_HOME -e JAVA_HOME_8_0_302_X64 -e INPUT_UPLOAD-FROM -e INPUT_UPLOAD-TO -e INPUT_SKICKA-TOKENCACHE-JSON -e INPUT_GOOGLE-CLIENT-ID -e INPUT_GOOGLE-CLIENT-SECRET -e INPUT_REMOVE-OUTDATED -e SKICKA_TOKENCACHE_JSON -e UPLOAD_FROM -e UPLOAD_TO -e REMOVE_OUTDATED -e GOOGLE_CLIENT_ID -e GOOGLE_CLIENT_SECRET -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/vsla-android/vsla-android":"/github/workspace" mkrakowitzer/actions-googledrive:latest
Go to the following link in your browser:
https://accounts.google.com/o/oauth2/auth?client_id=***&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=st1628167409769403870

skicka: error with OAuth2 Authorization: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_request",
  "error_description": "Missing required parameter: code"
} 
Enter verification code: 

```

And here is my yml file

```yml
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload APK to Google Drive
        uses: mkrakowitzer/actions-googledrive@master
        with:
          upload-from: ./app/build/outputs/apk/core/debug
          upload-to: QA/VSLA-Apps
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          google-client-id: ${{ secrets.MWAKA_GOOGLE_DRIVE_CLIENT_ID }}
          google-client-secret: ${{ secrets.MWAKA_GOOGLE_DRIVE_CLIENT_SECRET }}
```
Any help on using this is much appreciated.
